### ISSUE TITLE
WARNING - MySQL connection lost! Using next worker...

### ISSUE THREAD

**Issue by PHXY-DEV** [osuripple/pep.py#1]
Evrytime when i start PEP.PY i get This Error,

Config:
[db]
host = localhost
username = root
password = unknownpassword123 <---- Fake Password
database = rippledb
workers = 4

[redis]
host = localhost
port = 6379
database = 0
password =

[server]
port = 5001
threads = 16
gzip = 1
gziplevel = 6
cikey = changeme

[mirror]
url = http://storage.ripple.moe
apikey = anotherkey

[debug]
enable = 0
packets = 0
time = 0

[sentry]
enable = 0
banchodns =
ircdns =

[discord]
enable = 0
boturl =
devgroup =

[datadog]
enable = 0
apikey =
appkey =

[irc]
enable = 1
port = 6667
hostname = ripple

[localize]
enable = 1
ipapiurl = http://ip.zxq.co

Is this a Server side bug or A Python?
Python3.5 installed.

**Comment by PHXY-DEV** [comment]
I tried alredy Older version... No Fix...

**Comment by thehowl** [comment]
No support is provided for the code that we publish.
